share_directories:
  - path: /srv/
    options:
      - rw
      - sync
      - no_subtree_check
      - no_root_squash
    allowed_clients:
      - 192.168.0.80
      - 192.168.0.81
    should_mount: True
    remote_disk:
      id: /dev/sda1
      filetype: ext4